server:
    port: 9030

logging:
    level:
        org.springframework.security: DEBUG

security:
    oauth2:
        resource:
            user-info-uri: http://localhost:5000/uaa/users/current
        client:
            clientId: ytranslate-service
            clientSecret: password
            accessTokenUri: http://localhost:5000/uaa/oauth/token
            grant-type: client_credentials
            scope: server

#yandex dict
yandex:
  client:
    dict:
      root:
        url: {YANDEX_DICT_URL}
      key: {YANDEX_DICT_KEY}
      lang: en-ru
