server:
  port: 9040

logging:
  level:
    org.springframework.security: DEBUG

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current
    client:
      clientId: learn-service
      clientSecret: password
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server