server:
  port: 9030

logging:
  level:
    org.springframework.security: DEBUG

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current
    client:
      clientId: y_translate-service
      clientSecret: password
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

#yandex dict
yandex:
  client:
    dict:
      root:
        url: https://dictionary.yandex.net/api/v1/dicservice.json/lookup
      key: dict.1.1.20160315T215735Z.efa2f0f9aa89f225.a1845d9073947ee2350a879d35deabc4caf1f99d
      lang: en-ru